# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-21 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='shreni_desc',
            field=models.TextField(null=True),
        ),
    ]
