# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-20 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plot',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='image2',
        ),
    ]
