# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-21 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0002_auto_20180820_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shreni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shreni', models.CharField(max_length=10, verbose_name='श्रेणी')),
                ('shreni_description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='plot',
            name='shreni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plot.Shreni'),
        ),
    ]
